# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 11:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать блок')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('birthday', models.CharField(max_length=20, verbose_name='Дата рождения')),
                ('birthplace', models.CharField(max_length=255, verbose_name='Место рождения')),
                ('hobbies', models.CharField(max_length=127, verbose_name='Хобби')),
                ('photo', models.ImageField(upload_to='about', verbose_name='Фотография')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=127, verbose_name='Телефон')),
                ('email', models.CharField(max_length=63, verbose_name='Email')),
                ('website', models.CharField(max_length=63, verbose_name='Веб-сайт')),
                ('short_info', models.CharField(max_length=255, verbose_name='Краткая информация')),
                ('long_info', models.CharField(max_length=4095, verbose_name='Полная информация')),
            ],
            options={
                'verbose_name': 'Блок Обо мне',
            },
        ),
        migrations.CreateModel(
            name='AwardRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('index', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('title', models.CharField(max_length=255, verbose_name='Название награды')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('date', models.CharField(max_length=63, verbose_name='Дата вручения')),
                ('image', models.ImageField(upload_to='award', verbose_name='Изображение награды')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='AwardsBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать блок')),
                ('description', models.CharField(max_length=4095, verbose_name='Описание, блок Награды')),
            ],
            options={
                'verbose_name': 'Блок Награды',
            },
        ),
        migrations.CreateModel(
            name='CVBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать блок')),
                ('link', models.FileField(help_text='рекомендуется формат PDF', upload_to='cv', verbose_name='Файл Резюме')),
                ('description', models.CharField(max_length=4095, verbose_name='Описание для ссылки с резюме')),
            ],
            options={
                'verbose_name': 'Блок Резюме',
            },
        ),
        migrations.CreateModel(
            name='EducationBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать блок')),
                ('description', models.CharField(max_length=4095, verbose_name='Описание, блок Образование')),
            ],
            options={
                'verbose_name': 'Блок Образование',
            },
        ),
        migrations.CreateModel(
            name='EducationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('index', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('grade', models.CharField(max_length=127, verbose_name='Степень, звание')),
                ('university_name', models.CharField(max_length=255, verbose_name='Название учебного заведения')),
                ('country', models.CharField(max_length=127, verbose_name='Страна')),
                ('date_period', models.CharField(max_length=255, verbose_name='Период обучения')),
                ('description', models.CharField(max_length=511, verbose_name='Описание')),
                ('education_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.EducationBlock')),
            ],
            options={
                'verbose_name': 'Запись об образовании',
                'verbose_name_plural': 'Записи об образовании',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='GetInTouchBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать блок')),
                ('description', models.CharField(max_length=4095, verbose_name='Описание')),
                ('description_social', models.CharField(max_length=4095, verbose_name='Описание (соц. сети)')),
                ('signature', models.ImageField(upload_to='common', verbose_name='Изображение подписи')),
            ],
            options={
                'verbose_name': 'Блок Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='MainSliderBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать блок')),
            ],
            options={
                'verbose_name': 'Блок Слайдер',
            },
        ),
        migrations.CreateModel(
            name='PortfolioBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать блок')),
                ('description', models.CharField(max_length=4095, verbose_name='Описание, блок Портфолио')),
            ],
            options={
                'verbose_name': 'Блок Портфолио',
            },
        ),
        migrations.CreateModel(
            name='PortfolioRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('index', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('header', models.CharField(max_length=127, verbose_name='Заголовок')),
                ('subHeader', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('image', models.ImageField(upload_to='portfolio', verbose_name='Изображение работы')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на работу')),
                ('portfolio_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.PortfolioBlock')),
            ],
            options={
                'verbose_name': 'Запись в портфолио',
                'verbose_name_plural': 'Записи в портфолио',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='PortfolioType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('name', models.CharField(max_length=31, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип работы в портфолио',
                'verbose_name_plural': 'Типы работы в портфолио',
            },
        ),
        migrations.CreateModel(
            name='ProcessBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать блок')),
                ('description', models.CharField(max_length=4095, verbose_name='Описание, блок Процессы')),
                ('background', models.ImageField(upload_to='process', verbose_name='Фоновое изображение')),
            ],
            options={
                'verbose_name': 'Блок Процессы',
            },
        ),
        migrations.CreateModel(
            name='ProcessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('index', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=63, verbose_name='Название процесса')),
                ('icon', models.CharField(help_text='(FontAwesome)', max_length=31, verbose_name='Класс иконки')),
                ('process_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.ProcessBlock')),
            ],
            options={
                'verbose_name': 'Запись о процессе',
                'verbose_name_plural': 'Записи о процессах',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='ServiceBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать блок')),
                ('description', models.CharField(max_length=4095, verbose_name='Описание блока')),
                ('background', models.ImageField(upload_to='service', verbose_name='Фоновое изображение')),
            ],
            options={
                'verbose_name': 'Блок Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('description', models.CharField(max_length=1023, verbose_name='Описание услуги')),
                ('icon', models.CharField(help_text='(FontAwesome)', max_length=31, verbose_name='Класс иконки')),
                ('service_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.ServiceBlock')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showSectionButtons', models.BooleanField(verbose_name='Показывать кнопки секций')),
                ('feedback_mail', models.EmailField(help_text='Почта, куда отправлять сообщения из формы обратной связи', max_length=127, verbose_name='Основной Email')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='SkillBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать блок')),
                ('description', models.CharField(max_length=4095, verbose_name='Описание блока')),
                ('background', models.ImageField(upload_to='service', verbose_name='Фоновое изображение')),
            ],
            options={
                'verbose_name': 'Блок Навыки',
            },
        ),
        migrations.CreateModel(
            name='SkillRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('index', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('title', models.CharField(max_length=127, verbose_name='Название')),
                ('persent', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процентное соотношение')),
                ('skill_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.SkillBlock')),
            ],
            options={
                'verbose_name': 'Запись о навыке',
                'verbose_name_plural': 'Записи о навыках',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='SlideRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('index', models.PositiveSmallIntegerField(blank=True, help_text='В этом порядке будут показаны слайды на первом экране', null=True, verbose_name='Номер слайда')),
                ('image', models.ImageField(help_text='Не менее 1920px в ширину', upload_to='main_slider', verbose_name='Изображение слайда')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subheader', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('first_slogan', models.CharField(max_length=255, verbose_name='Слоган')),
                ('second_slogan', models.CharField(max_length=255, verbose_name='Второй слоган')),
                ('main_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.MainSliderBlock')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='SocialRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('index', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('link', models.URLField(max_length=255, verbose_name='Ссылка')),
                ('type', models.CharField(choices=[('vk', 'Вконтакте'), ('fb', 'Facebook'), ('li', 'Linked.In'), ('gp', 'Google Plus'), ('ig', 'Instagram'), ('bh', 'Behance'), ('fl', 'Freelance')], max_length=10, verbose_name='Тип соц.сети')),
                ('getintouch_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.GetInTouchBlock')),
            ],
            options={
                'verbose_name': 'Запись о соц.сети',
                'verbose_name_plural': 'Записи о соц.сетях',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='TestimonialRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('index', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=127, verbose_name='Имя рекомендателя')),
                ('companyName', models.CharField(max_length=127, verbose_name='Название компании')),
                ('text', models.CharField(max_length=1023, verbose_name='Текст рекомендации')),
            ],
            options={
                'verbose_name': ('Рекомендация',),
                'verbose_name_plural': ('Рекомендации',),
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='TestimonialsBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать блок')),
            ],
            options={
                'verbose_name': 'Блок Рекомендации',
            },
        ),
        migrations.CreateModel(
            name='VideoBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Отображать блок')),
                ('video', models.FileField(blank=True, null=True, upload_to='video', verbose_name='Файл видео')),
                ('video_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на видео')),
                ('video_title', models.CharField(max_length=1023, verbose_name='Текст над видео')),
                ('video_footer', models.CharField(max_length=1023, verbose_name='Текст под видео')),
                ('background_image', models.ImageField(upload_to='video', verbose_name='Фоновое изображение для блока видео')),
            ],
            options={
                'verbose_name': 'Блок Видео',
            },
        ),
        migrations.CreateModel(
            name='WorkExperienceBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать блок')),
                ('description', models.CharField(max_length=4095, verbose_name='Описание блока')),
            ],
            options={
                'verbose_name': 'Блок Опыт работы',
            },
        ),
        migrations.CreateModel(
            name='WorkExperienceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('index', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('companyName', models.CharField(max_length=127, verbose_name='Название компании')),
                ('position', models.CharField(max_length=127, verbose_name='Должность')),
                ('datePeriod', models.CharField(max_length=127, verbose_name='Период работы')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('companyUrl', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на сайт компании')),
                ('work_experience_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.WorkExperienceBlock')),
            ],
            options={
                'verbose_name': 'Запись об опыте работы',
                'verbose_name_plural': 'Записи об опыте работы',
                'ordering': ('index',),
            },
        ),
        migrations.AddField(
            model_name='testimonialrecord',
            name='testimonial_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.TestimonialsBlock'),
        ),
        migrations.AddField(
            model_name='portfoliorecord',
            name='portfolio_type',
            field=models.ManyToManyField(related_name='portfolio_types', to='main.PortfolioType', verbose_name='Типы работ'),
        ),
        migrations.AddField(
            model_name='awardrecord',
            name='award_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.AwardsBlock'),
        ),
    ]
