# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161101_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperiencerecord',
            old_name='datePeriod',
            new_name='date_period',
        ),
    ]
