# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161101_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardrecord',
            options={'ordering': ('index',), 'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='awardsblock',
            options={'verbose_name': 'Блок Достижения', 'verbose_name_plural': 'Блок Достижения'},
        ),
        migrations.RenameField(
            model_name='cvblock',
            old_name='link',
            new_name='cv',
        ),
        migrations.RemoveField(
            model_name='aboutmeblock',
            name='website',
        ),
        migrations.AddField(
            model_name='aboutmeblock',
            name='skype',
            field=models.CharField(default='', max_length=63, verbose_name='Skype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='awardrecord',
            name='award_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.AwardsBlock', verbose_name='Блок достижений'),
        ),
        migrations.AlterField(
            model_name='awardrecord',
            name='image',
            field=models.ImageField(upload_to='award', verbose_name='Изображение достижения'),
        ),
        migrations.AlterField(
            model_name='awardrecord',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название достижения'),
        ),
        migrations.AlterField(
            model_name='awardsblock',
            name='description',
            field=models.CharField(max_length=4095, verbose_name='Описание, блок Достижения'),
        ),
    ]
